/**
 *
 * @author Havoc
 */
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

public class IU_inventario extends javax.swing.JFrame {
private int fila;
private int tabla;
private static String name;
private static String pass;
private static List<String> id = new ArrayList<>();

    public IU_inventario() {      
        initComponents();
    }
    
    public IU_inventario(String name, String pass) {
        this.name=name;
        this.pass=pass;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab_panel = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_bases = new javax.swing.JTable();
        act_bases = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_cajas = new javax.swing.JTable();
        act_cajas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_flores = new javax.swing.JTable();
        act_flores = new javax.swing.JButton();
        Reg_Venta = new javax.swing.JButton();
        Sel_producto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla_bases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Descripción", "Cantidad", "Costo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_bases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_basesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabla_bases);

        act_bases.setText("Actualizar");
        act_bases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                act_basesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(act_bases)
                        .addGap(0, 846, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(act_bases)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tab_panel.addTab("Bases", jPanel3);

        tabla_cajas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Descripción", "Cantidad", "Dimensiones", "Rafia cm", "Costo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_cajas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_cajasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabla_cajas);

        act_cajas.setText("Actualizar");
        act_cajas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                act_cajasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(act_cajas)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(act_cajas)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tab_panel.addTab("Cajas", jPanel2);

        tabla_flores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Descripción", "Cantidad", "Color", "Costo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_flores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_floresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_flores);

        act_flores.setText("Actualizar");
        act_flores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                act_floresMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(act_flores)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(act_flores)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        tab_panel.addTab("Flores", jPanel1);

        Reg_Venta.setText("Registrar venta");
        Reg_Venta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Reg_VentaMouseClicked(evt);
            }
        });

        Sel_producto.setText("Seleccionar producto");
        Sel_producto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sel_productoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Sel_producto)
                .addGap(110, 110, 110)
                .addComponent(Reg_Venta)
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sel_producto)
                    .addComponent(Reg_Venta))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void act_cajasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_act_cajasMouseClicked
    String[] registro=null,aux=null;
    int cont=0;
                                //Utiliza el servicio para solictar información completa de las cajas
    Inventario inventario = new Inventario("Cajas",name,pass);  
    registro=inventario.get();
    for(int i=0;i<registro.length;i++)
        {
        aux=registro[i].split(", ");
        
        tabla_cajas.setValueAt(aux[0],cont,0);
        tabla_cajas.setValueAt(aux[1],cont,1);
        tabla_cajas.setValueAt(aux[2],cont,2);
        tabla_cajas.setValueAt(aux[4],cont,3);
        tabla_cajas.setValueAt(aux[5],cont,4); 
        tabla_cajas.setValueAt(aux[3],cont,5); 
        cont++;
        }
    }//GEN-LAST:event_act_cajasMouseClicked

    private void act_basesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_act_basesMouseClicked
    String[] registro=null,aux=null;
    int cont=0;
                                //Utiliza el servicio para solictar información completa de las bases
    Inventario inventario = new Inventario("Bases",name,pass);
    registro=inventario.get();
    for(int i=0;i<registro.length;i++)
        {
        aux=registro[i].split(", ");
        tabla_bases.setValueAt(aux[0],cont,0);
        tabla_bases.setValueAt(aux[1],cont,1);
        tabla_bases.setValueAt(aux[2],cont,2);
        tabla_bases.setValueAt(aux[3],cont,3);
        cont++;
        }
    }//GEN-LAST:event_act_basesMouseClicked

    private void act_floresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_act_floresMouseClicked
    String[] registro=null,aux=null;
    int cont=0;
                                    //Utiliza el servicio para solictar información completa de las flores
    Inventario inventario = new Inventario("Rosas",name,pass);
    registro=inventario.get();
    for(int i=0;i<registro.length;i++)
        {
        aux=registro[i].split(", ");
        tabla_flores.setValueAt(aux[0],cont,0);
        tabla_flores.setValueAt(aux[1],cont,1);
        tabla_flores.setValueAt(aux[2],cont,2);
        tabla_flores.setValueAt(aux[4],cont,3);
        tabla_flores.setValueAt(aux[3],cont,4); 
        cont++;
        }
    }//GEN-LAST:event_act_floresMouseClicked

    private void tabla_basesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_basesMouseClicked
    fila=tabla_bases.getSelectedRow();
    tabla=1;
    }//GEN-LAST:event_tabla_basesMouseClicked

    private void tabla_cajasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_cajasMouseClicked
    fila=tabla_cajas.getSelectedRow();
    tabla=2;
    }//GEN-LAST:event_tabla_cajasMouseClicked

    private void tabla_floresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_floresMouseClicked
    fila=tabla_flores.getSelectedRow();
    tabla=3;
    }//GEN-LAST:event_tabla_floresMouseClicked

    private void Sel_productoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sel_productoMouseClicked
    String aux=null;
    int error=0;
      
    switch(tabla)       //Se obtiene el serial del producto y se valida la cantidad en el inventario 
        {
        case 1:{                    
               aux=String.valueOf(tabla_bases.getValueAt(fila, 0));
               Integer.parseInt(String.valueOf(tabla_bases.getValueAt(fila, 2)));
               if(Integer.parseInt(String.valueOf(tabla_bases.getValueAt(fila, 2)))<=0)
                   {
                   error=1;    
                   }
               }break;
        case 2:{
                aux=String.valueOf(tabla_cajas.getValueAt(fila, 0));
               if(Integer.parseInt(String.valueOf(tabla_cajas.getValueAt(fila, 2)))<=0)
                   {
                   error=1;    
                   }
                }break;
        case 3:{
                aux=String.valueOf(tabla_flores.getValueAt(fila, 0));
               if(Integer.parseInt(String.valueOf(tabla_flores.getValueAt(fila, 2)))<=0)
                   {
                   error=1;    
                   }   
               }break;
        }
    if(error==0)
        {
        id.add(aux);
        JOptionPane.showMessageDialog(null, "item "+aux+" seleccionado");
        }
    else JOptionPane.showMessageDialog(null, "item "+aux+" no disponible");
    
    }//GEN-LAST:event_Sel_productoMouseClicked

    private void Reg_VentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Reg_VentaMouseClicked
    
    new IU_Venta(id,name,pass).setVisible(true); 
    dispose();
    }//GEN-LAST:event_Reg_VentaMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IU_inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IU_inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IU_inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IU_inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IU_inventario().setVisible(true);
            }
        });
    }
          
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reg_Venta;
    private javax.swing.JButton Sel_producto;
    private javax.swing.JButton act_bases;
    private javax.swing.JButton act_cajas;
    private javax.swing.JButton act_flores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane tab_panel;
    private javax.swing.JTable tabla_bases;
    private javax.swing.JTable tabla_cajas;
    private javax.swing.JTable tabla_flores;
    // End of variables declaration//GEN-END:variables
}
